"""fix auth_provider enum values

Revision ID: 472d9c94318f
Revises: a1b2c3d4e5f6
Create Date: 2025-11-17 21:27:45.242638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '472d9c94318f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Is email verified',
               existing_nullable=False)
    op.alter_column('users', 'auth_provider',
               existing_type=postgresql.ENUM('email', 'google', 'telegram', name='auth_provider_enum'),
               server_default=None,
               existing_comment='Authentication provider (email, google, telegram)',
               existing_nullable=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               comment='Telegram user ID (optional, for legacy users)',
               existing_comment='Telegram user ID',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Username (Telegram username or custom)',
               existing_comment='Telegram username',
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               comment='First name',
               existing_comment='Telegram first name',
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Last name',
               existing_comment='Telegram last name',
               existing_nullable=True)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_provider_id'), 'users', ['oauth_provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oauth_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Telegram last name',
               existing_comment='Last name',
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Telegram first name',
               existing_comment='First name',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Telegram username',
               existing_comment='Username (Telegram username or custom)',
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               comment='Telegram user ID',
               existing_comment='Telegram user ID (optional, for legacy users)',
               existing_nullable=True)
    op.alter_column('users', 'auth_provider',
               existing_type=postgresql.ENUM('email', 'google', 'telegram', name='auth_provider_enum'),
               server_default=sa.text("'email'::auth_provider_enum"),
               existing_comment='Authentication provider (email, google, telegram)',
               existing_nullable=False)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Is email verified',
               existing_nullable=False)
    # ### end Alembic commands ###
