"""add_progress_field_to_generation

Revision ID: 4e5ae641717a
Revises: 472d9c94318f
Create Date: 2025-11-18 17:08:33.265114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5ae641717a'
down_revision: Union[str, None] = '472d9c94318f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку с дефолтным значением для существующих записей
    op.add_column('generations', sa.Column('progress', sa.Integer(), nullable=False, server_default='0', comment='Прогресс генерации в процентах (0-100)'))
    # Убираем server_default после добавления колонки
    op.alter_column('generations', 'progress', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'progress')
    # ### end Alembic commands ###
